[env:attiny85env]
platform = atmelavr
board = attiny85
framework = arduino

board_build.f_cpu = 1000000L

upload_protocol = stk500v1
upload_flags =
	-P$UPLOAD_PORT
	-b$UPLOAD_SPEED
upload_port = /dev/cu.usbmodem1101
upload_speed = 19200
